### PR TITLE
Update example_lambda.py

### PR DESCRIPTION
**Pull request by ethanwlo**
Fixed Lambda_function flavor in example

### CODE REVIEW

**Review by anovis — APPROVED** [review]

**Review by davidyum — CHANGES_REQUESTED** [review]
nice good catch. Could you change line 24 as well

**Comment by eloucks** [comment]
Marked #79 as duplicate.  Let's get David's suggested change made, and we can merge.

**Comment by anovis** [comment]
also you will need to change extended lambda particle. it takes lambda as resource so should be lambda_function as well

**Comment by ethanwlo** [comment]
> nice good catch. Could you change line 24 as well

Done!

**Review by anovis — APPROVED** [review]

**Pull request merged**
