### PR TITLE
Parameterize cft template + tests

### PR DESCRIPTION
**Pull request by brianhlee**

### CODE REVIEW

**Comment by davidyum** [comment]
thanks for writing tests too 👍

**Review by davidyum — APPROVED** [review]

**Comment by davidyum** [comment]
once this is merged Ill add cloudformation to docs rst files and do a release

**Comment by davidyum** [comment]
@brianhlee actually while you are at it do you mind changing the old example file to .read() too when reading the yml file. I think its doing yml.load() and converting to str but this is better

**Comment by brianhlee** [comment]
done

**Review by ethanwlo — APPROVED** [review]
LGTM

**Pull request merged**
