### PR TITLE
Subnet public

### PR DESCRIPTION
**Pull request by anovis**
makes a subnet public by specifying a custom config value.

### CODE REVIEW

**Review by brianhlee — APPROVED** [review]
LGTM

**Comment by eloucks** [comment]
The way you do this works, but it also creates the subnet with the wrong setting initially, then corrects it with the sync state command. Wouldn't it be better to add the field to your start params so it can be included initially as well?

Also, you account for the subnet moving from private --> public, but not from public --> to private. You could include the opposite condition check to remove the option on update too.

**Comment by anovis** [comment]
boto3 doesn't let you set public when you create subnet.

**Comment by eloucks** [comment]
Ahh. Sorry, looked at obj attributes not the create_subnet method. That is an excellent reason :)

The change for public --> private looks good 👍

**Review by eloucks — APPROVED** [review]
LGTM

**Comment by anovis** [comment]
#75

**Pull request merged**
