### PR TITLE
Ecs task definition remove start param filters

### PR DESCRIPTION
**Pull request by anovis**
these are not needed since everything in aws_resource can be passed into the register_task_definition

### CODE REVIEW

**Review by brianhlee — APPROVED** [review]
LGTM

**Comment by eloucks** [comment]
Have we considered leaving it in? If ECS adds more options later on that aren't supported by boto3, we would have to add it back anyway. I could go either way on it.

**Comment by anovis** [comment]
I would prefer not to have it for now since it would be confusing to have it there without it doing anything and it would potentially get out of date

**Review by eloucks — APPROVED** [review]
Looks good.

**Pull request merged**
